[package]
name = "a1_2025_s2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uqbasejump"
path = "src/uqbasejump.rs"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.0"
subprocess = "0.2"
