[book]
authors = ["yaojun"]
language = "zh"
multilingual = false
src = "src"
title = "TCP Server"

[output.html]
default_theme = "light"

[preprocessor.toc]

[output.html.fold]
enable = true
level = 2
